2021-02-18 21:48:22.151377: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-02-18 21:48:22.151665: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-02-18 21:48:22.151681: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2021-02-18 21:48:25.311291: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-18 21:48:25.311326: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-18 21:48:25.311365: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c235.oscer.ou.edu): /proc/driver/nvidia/version does not exist
2021-02-18 21:48:25.311602: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-02-18 21:48:25.321324: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2297420000 Hz
2021-02-18 21:48:25.323493: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58f3b30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-18 21:48:25.323516: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "xor_base.py", line 150, in <module>
    execute_exp(args)
  File "xor_base.py", line 82, in execute_exp
    np.savetext('predictions_{}'.format(args.exp),predictions,delimeter=',')
AttributeError: module 'numpy' has no attribute 'savetext'
